services:
  - type: web
    name: muncher-frontend
    runtime: static
    rootDir: front-end
    buildCommand: yarn build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: "24"
      - key: ENABLE_COREPACK
        value: "1"