services:
  - type: web
    name: muncher-frontend
    runtime: static
    rootDir: front-end
    buildCommand: npm install -g corepack && corepack enable && yarn set version 4.9.2 && yarn install && yarn build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: "24"
      - key: ENABLE_COREPACK
        value: "1"
      - key: SKIP_INSTALL_DEPS
        value: "true"